### ISSUE TITLE
Repl panics on EOF (hit CTRL-D)

### ISSUE THREAD

**Issue by benknoble** [abrahampost/Butter#9]
```
 panic: runtime error: index out of range

goroutine 1 [running]:
main.(*Tokenizer).Advance(...)
        /Users/Knoble/go/src/github.com/abrahampost/Butter/tokenizer.go:413
main.(*Tokenizer).Tokenize(0xc00009ddb0, 0x0, 0x0, 0x0)
        /Users/Knoble/go/src/github.com/abrahampost/Butter/tokenizer.go:253 +0x1cb0
main.Run(0x0, 0x0, 0x1)
        /Users/Knoble/go/src/github.com/abrahampost/Butter/main.go:83 +0x99
main.RunPrompt()
        /Users/Knoble/go/src/github.com/abrahampost/Butter/main.go:73 +0x2a4
main.main()
        /Users/Knoble/go/src/github.com/abrahampost/Butter/main.go:38 +0xcd

```

**Comment by abrahampost** [comment]
Closed in #10
